INSERT INTO currency (name, symbol, code, "createdAt", "updatedAt")
VALUES
('US Dollar', '$', 'USD', NOW(), NOW()),
('Euro', '€', 'EUR', NOW(), NOW()),
('British Pound', '£', 'GBP', NOW(), NOW()),
('Kenyan Shilling', 'KSh', 'KES', NOW(), NOW()),
('Nigerian Naira', '₦', 'NGN', NOW(), NOW()),
('Ghanaian Cedi', '₵', 'GHS', NOW(), NOW()),
('South African Rand', 'R', 'ZAR', NOW(), NOW()),
('Japanese Yen', '¥', 'JPY', NOW(), NOW()),
('Chinese Yuan', '¥', 'CNY', NOW(), NOW()),
('Canadian Dollar', '$', 'CAD', NOW(), NOW()),
('Australian Dollar', '$', 'AUD', NOW(), NOW()),
('Indian Rupee', '₹', 'INR', NOW(), NOW()),
('Ugandan Shilling', 'USh', 'UGX', NOW(), NOW()),
('Tanzanian Shilling', 'TSh', 'TZS', NOW(), NOW()),
('Rwandan Franc', 'FRw', 'RWF', NOW(), NOW()),
('Ethiopian Birr', 'Br', 'ETB', NOW(), NOW()),
('Egyptian Pound', '£', 'EGP', NOW(), NOW()),
('Moroccan Dirham', 'د.م.', 'MAD', NOW(), NOW()),
('Algerian Dinar', 'دج', 'DZD', NOW(), NOW()),
('Tunisian Dinar', 'د.ت', 'TND', NOW(), NOW()),
('Libyan Dinar', 'ل.د', 'LYD', NOW(), NOW()),
('Sudanese Pound', '£', 'SDG', NOW(), NOW()),
('Zambian Kwacha', 'ZK', 'ZMW', NOW(), NOW()),
('Malawian Kwacha', 'MK', 'MWK', NOW(), NOW()),
('Botswana Pula', 'P', 'BWP', NOW(), NOW()),
('Mozambican Metical', 'MT', 'MZN', NOW(), NOW()),
('Angolan Kwanza', 'Kz', 'AOA', NOW(), NOW()),
('Namibian Dollar', '$', 'NAD', NOW(), NOW()),
('Zimbabwean Dollar', '$', 'ZWL', NOW(), NOW()),
('Seychellois Rupee', '₨', 'SCR', NOW(), NOW()),
('Mauritian Rupee', '₨', 'MUR', NOW(), NOW()),
('Cape Verdean Escudo', '$', 'CVE', NOW(), NOW()),
('Somali Shilling', 'Sh', 'SOS', NOW(), NOW()),
('Comorian Franc', 'CF', 'KMF', NOW(), NOW()),
('Djiboutian Franc', 'Fdj', 'DJF', NOW(), NOW()),
('Central African CFA Franc', 'FCFA', 'XAF', NOW(), NOW()),
('West African CFA Franc', 'CFA', 'XOF', NOW(), NOW()),
('Burundian Franc', 'FBu', 'BIF', NOW(), NOW()),
('Sierra Leonean Leone', 'Le', 'SLE', NOW(), NOW()),
('Liberian Dollar', '$', 'LRD', NOW(), NOW()),
('Cameroonian Franc', 'FCFA', 'XAF', NOW(), NOW()),
('Congolese Franc', 'FC', 'CDF', NOW(), NOW()),
('Guinean Franc', 'FG', 'GNF', NOW(), NOW()),
('Madagascar Ariary', 'Ar', 'MGA', NOW(), NOW()),
('Eswatini Lilangeni', 'E', 'SZL', NOW(), NOW()),
('Lesotho Loti', 'L', 'LSL', NOW(), NOW()),
('Burkina Faso Franc', 'CFA', 'XOF', NOW(), NOW()),
('Benin Franc', 'CFA', 'XOF', NOW(), NOW()),
('Togolese Franc', 'CFA', 'XOF', NOW(), NOW()),
('Niger Franc', 'CFA', 'XOF', NOW(), NOW()),
('Chadian Franc', 'CFA', 'XAF', NOW(), NOW()),
('Gabonese Franc', 'CFA', 'XAF', NOW(), NOW()),
('Equatorial Guinean Franc', 'CFA', 'XAF', NOW(), NOW()),
('Central African Republic Franc', 'CFA', 'XAF', NOW(), NOW()),
('Congolese (Brazzaville) Franc', 'CFA', 'XAF', NOW(), NOW()),
('São Tomé and Príncipe Dobra', 'Db', 'STN', NOW(), NOW()),
('Eritrean Nakfa', 'Nfk', 'ERN', NOW(), NOW()),
('Mauritanian Ouguiya', 'UM', 'MRU', NOW(), NOW()),
('South Sudanese Pound', '£', 'SSP', NOW(), NOW()),
('Qatari Riyal', 'ر.ق', 'QAR', NOW(), NOW()),
('Saudi Riyal', 'ر.س', 'SAR', NOW(), NOW()),
('United Arab Emirates Dirham', 'د.إ', 'AED', NOW(), NOW()),
('Kuwaiti Dinar', 'د.ك', 'KWD', NOW(), NOW()),
('Bahraini Dinar', 'ب.د', 'BHD', NOW(), NOW()),
('Omani Rial', 'ر.ع.', 'OMR', NOW(), NOW()),
('Israeli New Shekel', '₪', 'ILS', NOW(), NOW()),
('Turkish Lira', '₺', 'TRY', NOW(), NOW()),
('Iranian Rial', '﷼', 'IRR', NOW(), NOW()),
('Pakistani Rupee', '₨', 'PKR', NOW(), NOW()),
('Bangladeshi Taka', '৳', 'BDT', NOW(), NOW()),
('Sri Lankan Rupee', '₨', 'LKR', NOW(), NOW()),
('Nepalese Rupee', '₨', 'NPR', NOW(), NOW()),
('Bhutanese Ngultrum', 'Nu.', 'BTN', NOW(), NOW()),
('Maldivian Rufiyaa', 'Rf', 'MVR', NOW(), NOW()),
('Singapore Dollar', '$', 'SGD', NOW(), NOW()),
('Malaysian Ringgit', 'RM', 'MYR', NOW(), NOW()),
('Indonesian Rupiah', 'Rp', 'IDR', NOW(), NOW()),
('Philippine Peso', '₱', 'PHP', NOW(), NOW()),
('Vietnamese Dong', '₫', 'VND', NOW(), NOW()),
('Thai Baht', '฿', 'THB', NOW(), NOW()),
('Cambodian Riel', '៛', 'KHR', NOW(), NOW()),
('Myanmar Kyat', 'K', 'MMK', NOW(), NOW()),
('Laotian Kip', '₭', 'LAK', NOW(), NOW()),
('Brunei Dollar', '$', 'BND', NOW(), NOW()),
('New Zealand Dollar', '$', 'NZD', NOW(), NOW()),
('Fijian Dollar', '$', 'FJD', NOW(), NOW()),
('Papua New Guinean Kina', 'K', 'PGK', NOW(), NOW()),
('Samoan Tala', 'T', 'WST', NOW(), NOW()),
('Tongan Paʻanga', 'T$', 'TOP', NOW(), NOW()),
('Solomon Islands Dollar', '$', 'SBD', NOW(), NOW()),
('Vanuatu Vatu', 'Vt', 'VUV', NOW(), NOW()),
('East Caribbean Dollar', '$', 'XCD', NOW(), NOW()),
('Jamaican Dollar', '$', 'JMD', NOW(), NOW()),
('Barbadian Dollar', '$', 'BBD', NOW(), NOW()),
('Bahamian Dollar', '$', 'BSD', NOW(), NOW()),
('Trinidad and Tobago Dollar', '$', 'TTD', NOW(), NOW()),
('Haitian Gourde', 'G', 'HTG', NOW(), NOW()),
('Cuban Peso', '$', 'CUP', NOW(), NOW()),
('Dominican Peso', '$', 'DOP', NOW(), NOW()),
('Belize Dollar', '$', 'BZD', NOW(), NOW()),
('Honduran Lempira', 'L', 'HNL', NOW(), NOW()),
('Guatemalan Quetzal', 'Q', 'GTQ', NOW(), NOW()),
('Nicaraguan Córdoba', 'C$', 'NIO', NOW(), NOW()),
('Costa Rican Colón', '₡', 'CRC', NOW(), NOW()),
('Panamanian Balboa', 'B/.', 'PAB', NOW(), NOW()),
('Mexican Peso', '$', 'MXN', NOW(), NOW()),
('Argentine Peso', '$', 'ARS', NOW(), NOW()),
('Brazilian Real', 'R$', 'BRL', NOW(), NOW()),
('Chilean Peso', '$', 'CLP', NOW(), NOW()),
('Colombian Peso', '$', 'COP', NOW(), NOW()),
('Peruvian Sol', 'S/', 'PEN', NOW(), NOW()),
('Uruguayan Peso', '$', 'UYU', NOW(), NOW()),
('Paraguayan Guarani', '₲', 'PYG', NOW(), NOW()),
('Bolivian Boliviano', 'Bs', 'BOB', NOW(), NOW()),
('Venezuelan Bolívar', 'Bs.', 'VES', NOW(), NOW()),
('Surinamese Dollar', '$', 'SRD', NOW(), NOW()),
('Guyanaese Dollar', '$', 'GYD', NOW(), NOW());